---
- name: Install Security Updates on Ubuntu Servers
  hosts: all
  gather_facts: yes

  vars:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    smtp_user: "saymypc@gmail.com"
    smtp_pass: "abnitwbrkeyhqfig"
    email_to: "{{ email_recipient }}"  # This should be provided as an extra var when running the playbook
    current_date: "{{ ansible_date_time.date }}"
    current_time: "{{ ansible_date_time.time }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install unattended-upgrades package
      apt:
        name: unattended-upgrades
        state: present

    - name: Run unattended security upgrades
      command: unattended-upgrades -d --dry-run
      register: security_updates
      changed_when: "'Packages that will be upgraded:' in security_updates.stdout"

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Generate report
      set_fact:
        update_report: |
          Security Updates Report for {{ ansible_hostname }}
          ------------------------------------------------
          Date: {{ current_date }}
          Time: {{ current_time }}
          
          Updates Status:
          {{ security_updates.stdout }}
          
          Reboot Required: {{ reboot_required.stat.exists | bool }}

    - name: Send email notification
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ smtp_pass }}"
        to: "{{ email_to }}"
        from: "{{ smtp_user }}"
        subject: "Security Updates Report - {{ ansible_hostname }}"
        body: "{{ update_report }}"
        secure: starttls
      delegate_to: localhost
