---
- name: Install Security Updates on Ubuntu Servers
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    smtp_user: "saymypc@gmail.com"
    smtp_pass: "abnitwbrkeyhqfig"
    email_to: "{{ email_recipient }}"  # This should be provided as an extra var when running the playbook
    current_date: "{{ ansible_date_time.date }}"
    current_time: "{{ ansible_date_time.time }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install security updates only
      apt:
        upgrade: security
        force_apt_get: yes
      register: security_updates

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Generate report
      set_fact:
        update_report: |
          Security Updates Report for {{ ansible_hostname }}
          ------------------------------------------------
          Date: {{ ansible_date_time.iso8601 }}
          
          Updates Installed:
          {{ security_updates.stdout }}
          
          Changes Made:
          - Packages upgraded: {{ security_updates.upgraded | default(0) }}
          - Packages newly installed: {{ security_updates.installed | default(0) }}
          - Packages removed: {{ security_updates.removed | default(0) }}
          
          Reboot Required: {{ reboot_required.stat.exists | bool }}

    - name: Send email notification
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        to: "{{ email_to }}"
        from: "{{ email_from }}"
        subject: "Security Updates Report - {{ ansible_hostname }}"
        body: "{{ update_report }}"
        secure: starttls
      delegate_to: localhost
